[versions]
apacheMina = "2.9.2"
assertj = "3.23.1"
junit = "5.9.0"
gradlePublishPlugin = "1.1.0"

[libraries]
sshdApacheMina = { group = "org.apache.sshd", name = "sshd-core", version.ref = "apacheMina"}
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj"}
junitJupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit"}

[plugins]
gradlePublishPlugin = { id = "com.gradle.plugin-publish", version.ref = "gradlePublishPlugin"}